Repository mun-lang/mun, pull requests merged in 2020-10, with the labels that each got.

#263 feat: add mdbook plugin for testing mun code in book
  book/book.toml
  book/listings/ch01-getting-started/listing01.mun
  book/listings/ch01-getting-started/listing02.mun
  book/src/ch01-02-hello-fibonacci.md
  book/src/ch01-03-hello-hot-reloading.md
  book/src/ch02-01-values-and-types.md
  book/src/ch02-02-functions.md
  book/src/ch02-03-control-flow.md
  book/src/ch02-04-extern-fn.md
  book/src/ch03-04-hot-reloading-structs.md
  crates/mun_mdbook_test_plugin/Cargo.toml
  crates/mun_mdbook_test_plugin/src/main.rs
Labels: type: feat

#278 fix: dont run mun tests on CI
  book/book.toml
  book/ci/build
Labels: pri: high, type: fix

#280 fix: 7zip issues
  .github/actions/install-llvm/dist/index.js
  .github/actions/install-llvm/externals/7zr.exe
  .github/actions/install-llvm/index.js
  .github/actions/install-llvm/package-lock.json
  .github/actions/install-llvm/package.json
  .github/workflows/ci.yml
Labels: pri: intermediate, type: fix

#279 bump: rust 1.47
  crates/mun_abi/src/type_info.rs
  crates/mun_compiler/src/driver/display_color.rs
  crates/mun_hir/src/expr.rs
  crates/mun_hir/src/ty.rs
  crates/mun_hir/src/ty/lower.rs
  crates/mun_syntax/src/ast/extensions.rs
  crates/mun_syntax/src/ast/generated.rs
  crates/mun_syntax/src/ast/generated.rs.tera
  crates/mun_syntax/src/parsing/grammar/paths.rs
  crates/mun_syntax/src/syntax_kind.rs
  crates/mun_syntax/src/syntax_kind/generated.rs
  crates/mun_syntax/src/syntax_kind/generated.rs.tera
  rust-toolchain
Labels: pri: low, type: improvement

#286 feat(codegen): add AsValue macro support for enums
  crates/mun_codegen/Cargo.toml
  crates/mun_codegen/src/ir/types.rs
  crates/mun_codegen/src/mock.rs
  crates/mun_codegen/src/value/array_value.rs
  crates/mun_codegen/src/value/float_value.rs
  crates/mun_codegen/src/value/int_value.rs
  crates/mun_codegen/src/value/mod.rs
  crates/mun_codegen/src/value/pointer_value.rs
  crates/mun_codegen/src/value/string.rs
  crates/mun_codegen_macros/Cargo.toml
  crates/mun_codegen_macros/src/lib.rs
Labels: type: feat
