Repository mun-lang/mun, pull requests merged in 2020-06, with the labels that each got.

#214 fix: Rust v1.44 cargo fmt and clippy errors
  crates/mun_hir/src/expr.rs
  crates/mun_syntax/src/syntax_kind/generated.rs
  crates/mun_syntax/src/syntax_kind/generated.rs.tera
Labels: type: fix

#221 fix(codegen): crash on missing nested private function
  crates/mun_codegen/src/ir/dispatch_table.rs
  crates/mun_codegen/src/snapshots/test__nested_private_extern_fn.snap
  crates/mun_codegen/src/snapshots/test__nested_private_fn.snap
  crates/mun_codegen/src/snapshots/test__nested_private_recursive_fn.snap
  crates/mun_codegen/src/snapshots/test__nested_private_recursive_fn_with_args.snap
  crates/mun_codegen/src/test.rs
Labels: pri: high, type: fix

#229 fix: fixes issue #228
  crates/mun_codegen/src/ir/body.rs
  crates/mun_codegen/src/snapshots/test__issue_228.snap
  crates/mun_codegen/src/snapshots/test__issue_228_never_if.snap
  crates/mun_codegen/src/test.rs
Labels: type: fix

#223 feature: foundation for projects
  crates/mun/Cargo.toml
  crates/mun/src/lib.rs
  crates/mun/src/main.rs
  crates/mun/tests/integration.rs
  crates/mun_codegen/src/assembly.rs
  crates/mun_codegen/src/code_gen.rs
  crates/mun_codegen/src/db.rs
  crates/mun_codegen/src/lib.rs
  crates/mun_codegen/src/mock.rs
  crates/mun_compiler/Cargo.toml
  crates/mun_compiler/src/db.rs
  crates/mun_compiler/src/diagnostics.rs
  crates/mun_compiler/src/driver.rs
  crates/mun_compiler/src/driver/display_color.rs
  crates/mun_compiler/src/lib.rs
  crates/mun_compiler_daemon/Cargo.toml
  crates/mun_compiler_daemon/src/lib.rs
  crates/mun_hir/src/input.rs
  crates/mun_hir/src/mock.rs
  crates/mun_project/Cargo.toml
  crates/mun_project/src/lib.rs
  crates/mun_project/src/manifest.rs
  crates/mun_project/src/manifest/toml.rs
  crates/mun_project/src/package.rs
  crates/mun_project/tests/parse.rs
  crates/mun_project/tests/resources/mun.toml
  crates/mun_project/tests/resources/src/main.mun
  crates/mun_runtime/benches/util/mod.rs
  crates/mun_runtime/tests/util.rs
  crates/mun_runtime_capi/src/tests.rs
Labels: type: feat
