Repository mun-lang/mun, pull requests merged in 2020-09, with the labels that each got.

#264 fix: never return type in let initializer
  crates/mun_codegen/src/ir/body.rs
  crates/mun_codegen/src/snapshots/mun_codegen__test__issue_262.snap
  crates/mun_codegen/src/test.rs
Labels: type: fix

#266 refactor: use Idx<T> instead of macro in arena
  crates/mun_codegen/src/ir/body.rs
  crates/mun_hir/src/adt.rs
  crates/mun_hir/src/arena.rs
  crates/mun_hir/src/arena/map.rs
  crates/mun_hir/src/code_model.rs
  crates/mun_hir/src/expr.rs
  crates/mun_hir/src/expr/scope.rs
  crates/mun_hir/src/lib.rs
  crates/mun_hir/src/raw.rs
  crates/mun_hir/src/resolve.rs
  crates/mun_hir/src/source_id.rs
  crates/mun_hir/src/ty/infer.rs
  crates/mun_hir/src/ty/lower.rs
  crates/mun_hir/src/type_ref.rs
Labels: type: refactor

#267 misc: split database and added docs
  book/src/SUMMARY.md
  book/src/ch04-00-developer-docs.md
  book/src/ch04-01-salsa-super-traits.png
  book/src/ch04-01-salsa.md
  crates/mun_codegen/src/mock.rs
  crates/mun_compiler/src/db.rs
  crates/mun_compiler/src/driver.rs
  crates/mun_hir/src/db.rs
  crates/mun_hir/src/expr/validator/tests.rs
  crates/mun_hir/src/in_file.rs
  crates/mun_hir/src/lib.rs
  crates/mun_hir/src/mock.rs
  crates/mun_hir/src/source_id.rs
  crates/mun_hir/src/ty/tests.rs
  crates/mun_language_server/src/db.rs
  crates/mun_language_server/src/diagnostics.rs
Labels: type: docs

#270 improvement: bump smol_str dependency to 0.1.17
  crates/mun_hir/src/name.rs
  crates/mun_syntax/Cargo.toml
Labels: type: improvement

#271 feature: refactored RawItems into ItemTree
  crates/mun_hir/src/adt.rs
  crates/mun_hir/src/code_model.rs
  crates/mun_hir/src/code_model/src.rs
  crates/mun_hir/src/db.rs
  crates/mun_hir/src/expr/validator/tests.rs
  crates/mun_hir/src/ids.rs
  crates/mun_hir/src/item_tree.rs
  crates/mun_hir/src/item_tree/lower.rs
  crates/mun_hir/src/item_tree/snapshots/mun_hir__item_tree__tests__top_level_items.snap
  crates/mun_hir/src/item_tree/tests.rs
  crates/mun_hir/src/lib.rs
  crates/mun_hir/src/source_id.rs
  crates/mun_hir/src/ty/tests.rs
Labels: type: refactor

#272 feature: adds fixtures to support multiple files from string
  crates/mun_hir/Cargo.toml
  crates/mun_hir/src/expr/validator/tests.rs
  crates/mun_hir/src/fixture.rs
  crates/mun_hir/src/item_tree/tests.rs
  crates/mun_hir/src/lib.rs
  crates/mun_hir/src/mock.rs
  crates/mun_hir/src/tests.rs
  crates/mun_hir/src/ty/tests.rs
  crates/mun_test/Cargo.toml
  crates/mun_test/src/fixture.rs
  crates/mun_test/src/lib.rs
Labels: type: feat
