Repository mun-lang/mun, pull requests merged in 2021-01, with the labels that each got.

#291 bump: rust 1.49
  crates/mun_codegen/src/code_gen/symbols.rs
  crates/mun_hir/src/expr/scope.rs
  crates/mun_lld/src/lib.rs
  crates/mun_syntax/src/parsing/lexer/classes.rs
  rust-toolchain
Labels: pri: intermediate, type: improvement

#292 fix: shorten commit hash with environment file
  .github/workflows/release.yml
Labels: pri: high, type: fix

#296 feat(cli): add option to emit IR
  crates/mun/Cargo.toml
  crates/mun/src/lib.rs
  crates/mun/src/ops/build.rs
  crates/mun/src/ops/init.rs
  crates/mun/src/ops/new.rs
  crates/mun/tests/integration.rs
  crates/mun_codegen/src/assembly.rs
  crates/mun_codegen/src/code_gen.rs
  crates/mun_codegen/src/code_gen/module_builder.rs
  crates/mun_codegen/src/code_gen/object_file.rs
  crates/mun_codegen/src/db.rs
  crates/mun_codegen/src/lib.rs
  crates/mun_codegen/src/test.rs
  crates/mun_compiler/Cargo.toml
  crates/mun_compiler/src/db.rs
  crates/mun_compiler/src/diagnostics_snippets.rs
  crates/mun_compiler/src/driver.rs
  crates/mun_compiler/src/driver/config.rs
  crates/mun_compiler/src/lib.rs
Labels: type: feat

#294 feat(language server): integrated new vfs
  crates/mun_codegen/Cargo.toml
  crates/mun_codegen/src/code_gen/module_builder.rs
  crates/mun_codegen/src/mock.rs
  crates/mun_compiler/Cargo.toml
  crates/mun_compiler/src/diagnostics_snippets.rs
  crates/mun_compiler/src/driver.rs
  crates/mun_compiler/src/lib.rs
  crates/mun_compiler_daemon/src/lib.rs
  crates/mun_hir/Cargo.toml
  crates/mun_hir/src/code_model/package.rs
  crates/mun_hir/src/db.rs
  crates/mun_hir/src/fixture.rs
  crates/mun_hir/src/ids.rs
  crates/mun_hir/src/input.rs
  crates/mun_hir/src/lib.rs
  crates/mun_hir/src/module_tree.rs
  crates/mun_hir/src/name_resolution/path_resolution.rs
  crates/mun_hir/src/package_defs.rs
  crates/mun_hir/src/package_defs/collector.rs
  crates/mun_hir/src/package_set.rs
  crates/mun_language_server/Cargo.toml
  crates/mun_language_server/src/analysis.rs
  crates/mun_language_server/src/change.rs
  crates/mun_language_server/src/config.rs
  crates/mun_language_server/src/conversion.rs
  crates/mun_language_server/src/lib.rs
  crates/mun_language_server/src/main_loop.rs
  crates/mun_language_server/src/project_manifest.rs
  crates/mun_language_server/src/workspace.rs
  crates/mun_language_server/tests/support.rs
  crates/mun_paths/Cargo.toml
  crates/mun_paths/src/abs_path.rs
  crates/mun_paths/src/lib.rs
  crates/mun_project/src/package.rs
  crates/mun_project/tests/parse.rs
  crates/mun_vfs/Cargo.toml
  crates/mun_vfs/src/lib.rs
  crates/mun_vfs/src/monitor.rs
  crates/mun_vfs/src/monitor/notify_monitor.rs
  crates/mun_vfs/src/path_interner.rs
Labels: pri: intermediate, type: refactor

#295 feat(language server): removed async code and switched to lsp_server
  crates/mun_language_server/Cargo.toml
  crates/mun_language_server/src/analysis.rs
  crates/mun_language_server/src/cancelation.rs
  crates/mun_language_server/src/config.rs
  crates/mun_language_server/src/conversion.rs
  crates/mun_language_server/src/db.rs
  crates/mun_language_server/src/lib.rs
  crates/mun_language_server/src/main_loop.rs
  crates/mun_language_server/src/protocol.rs
  crates/mun_language_server/src/protocol/connection.rs
  crates/mun_language_server/src/protocol/error.rs
  crates/mun_language_server/src/protocol/message.rs
  crates/mun_language_server/src/protocol/stdio.rs
  crates/mun_language_server/src/state.rs
  crates/mun_language_server/src/state/protocol.rs
  crates/mun_language_server/src/state/protocol/dispatcher.rs
  crates/mun_language_server/src/state/utils.rs
  crates/mun_language_server/src/state/workspace.rs
  crates/mun_language_server/tests/initialization.rs
  crates/mun_language_server/tests/support.rs
  crates/mun_project/Cargo.toml
  crates/mun_project/src/lib.rs
  crates/mun_project/src/project_manifest.rs
  crates/mun_vfs/src/monitor.rs
Labels: pri: intermediate, type: refactor

#301 misc: adds logging to windows llvm install
  .github/actions/install-llvm/dist/index.js
  .github/actions/install-llvm/index.js
  .github/actions/install-llvm/package-lock.json
  .github/actions/install-llvm/package.json
  .github/workflows/ci.yml
Labels: type: improvement

#297 feature(lsp): adds document symbol provider
  crates/mun_language_server/Cargo.toml
  crates/mun_language_server/src/analysis.rs
  crates/mun_language_server/src/capabilities.rs
  crates/mun_language_server/src/conversion.rs
  crates/mun_language_server/src/file_structure.rs
  crates/mun_language_server/src/handlers.rs
  crates/mun_language_server/src/lib.rs
  crates/mun_language_server/src/state.rs
  crates/mun_language_server/src/state/protocol.rs
  crates/mun_language_server/src/state/protocol/dispatcher.rs
  crates/mun_language_server/src/symbol_kind.rs
  crates/mun_language_server/tests/initialization.rs
  crates/mun_language_server/tests/snapshots/initialization__document_symbols.snap
  crates/mun_language_server/tests/support.rs
  crates/mun_syntax/src/lib.rs
Labels: type: feat

#302 fix: manually extract llvm release to get more output
  .github/actions/install-llvm/dist/index.js
  .github/actions/install-llvm/index.js
Labels: type: fix
