Repository mun-lang/mun, pull requests merged in 2022-02, with the labels that each got.

#367 misc: bump Rust to 2021 edition
  crates/mun/Cargo.toml
  crates/mun_abi/Cargo.toml
  crates/mun_codegen/Cargo.toml
  crates/mun_codegen_macros/Cargo.toml
  crates/mun_compiler/Cargo.toml
  crates/mun_compiler_daemon/Cargo.toml
  crates/mun_diagnostics/Cargo.toml
  crates/mun_hir/Cargo.toml
  crates/mun_language_server/Cargo.toml
  crates/mun_libloader/Cargo.toml
  crates/mun_lld/Cargo.toml
  crates/mun_memory/Cargo.toml
  crates/mun_paths/Cargo.toml
  crates/mun_project/Cargo.toml
  crates/mun_runtime/Cargo.toml
  crates/mun_runtime/benches/wasm-sources/empty/Cargo.toml
  crates/mun_runtime/benches/wasm-sources/fibonacci/Cargo.toml
  crates/mun_runtime/src/lib.rs
  crates/mun_runtime_capi/Cargo.toml
  crates/mun_skeptic/Cargo.toml
  crates/mun_syntax/Cargo.toml
  crates/mun_target/Cargo.toml
  crates/mun_test/Cargo.toml
  crates/mun_vfs/Cargo.toml
  crates/tools/Cargo.toml
Labels: type: improvement, pri: low, exp: low

#351 misc: upgrade to LLVM 12.0.1
  .github/actions/install-llvm/dist/index.js
  .github/actions/install-llvm/index.js
  book/src/ch04-02-building-llvm.md
  crates/mun_codegen/Cargo.toml
  crates/mun_codegen/src/code_gen/symbols.rs
  crates/mun_codegen/src/intrinsics/macros.rs
  crates/mun_codegen/src/ir.rs
  crates/mun_codegen/src/ir/body.rs
  crates/mun_codegen/src/ir/dispatch_table.rs
  crates/mun_codegen/src/ir/ty.rs
  crates/mun_codegen/src/snapshots/mun_codegen__test__fibonacci.snap
  crates/mun_codegen/src/snapshots/mun_codegen__test__loop_break_expr.snap
  crates/mun_codegen/src/value/function_value.rs
  crates/mun_lld/Cargo.toml
  scripts/install-llvm.sh
Labels: type: improvement, pri: critical

#370 feat: make the runtime send
  book/listings/ch01-getting-started/listing04.rs
  book/listings/ch02-basic-concepts/listing02.rs
  book/listings/ch02-basic-concepts/listing03.rs
  book/listings/ch03-structs/listing11.rs
  book/listings/ch03-structs/listing12.rs
  book/listings/ch03-structs/listing14.rs
  crates/mun/src/ops/start.rs
  crates/mun/tests/integration.rs
  crates/mun_memory/src/gc/root_ptr.rs
  crates/mun_runtime/benches/benchmarks.rs
  crates/mun_runtime/benches/util/mod.rs
  crates/mun_runtime/examples/buoyancy.rs
  crates/mun_runtime/examples/fibonacci.rs
  crates/mun_runtime/src/adt.rs
  crates/mun_runtime/src/lib.rs
  crates/mun_runtime/tests/hot_reloading.rs
  crates/mun_runtime/tests/marshalling.rs
  crates/mun_runtime/tests/memory.rs
  crates/mun_runtime/tests/runtime.rs
  crates/mun_runtime/tests/threading.rs
  crates/mun_runtime/tests/util.rs
  crates/mun_skeptic/src/runtime.rs
  crates/mun_test/src/driver.rs
Labels: type: improvement
